# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  HeadPitch:
    has_velocity_limits: true
    max_velocity: 5.759586525
    has_acceleration_limits: false
    max_acceleration: 0
  HeadYaw:
    has_velocity_limits: true
    max_velocity: 5.759586525
    has_acceleration_limits: false
    max_acceleration: 0
  LAnklePitch:
    has_velocity_limits: true
    max_velocity: 4.712388975
    has_acceleration_limits: false
    max_acceleration: 0
  LAnkleRoll:
    has_velocity_limits: true
    max_velocity: 4.712388975
    has_acceleration_limits: false
    max_acceleration: 0
  LElbowPitch:
    has_velocity_limits: true
    max_velocity: 6.597344565
    has_acceleration_limits: false
    max_acceleration: 0
  LHipPitch:
    has_velocity_limits: true
    max_velocity: 4.712388975
    has_acceleration_limits: false
    max_acceleration: 0
  LHipRoll:
    has_velocity_limits: true
    max_velocity: 4.712388975
    has_acceleration_limits: false
    max_acceleration: 0
  LHipYaw:
    has_velocity_limits: true
    max_velocity: 4.712388975
    has_acceleration_limits: false
    max_acceleration: 0
  LKneePitch:
    has_velocity_limits: true
    max_velocity: 4.712388975
    has_acceleration_limits: false
    max_acceleration: 0
  LShoulderPitch:
    has_velocity_limits: true
    max_velocity: 6.597344565
    has_acceleration_limits: false
    max_acceleration: 0
  LShoulderRoll:
    has_velocity_limits: true
    max_velocity: 6.597344565
    has_acceleration_limits: false
    max_acceleration: 0
  RAnklePitch:
    has_velocity_limits: true
    max_velocity: 4.712388975
    has_acceleration_limits: false
    max_acceleration: 0
  RAnkleRoll:
    has_velocity_limits: true
    max_velocity: 4.712388975
    has_acceleration_limits: false
    max_acceleration: 0
  RElbowPitch:
    has_velocity_limits: true
    max_velocity: 6.597344565
    has_acceleration_limits: false
    max_acceleration: 0
  RHipPitch:
    has_velocity_limits: true
    max_velocity: 4.712388975
    has_acceleration_limits: false
    max_acceleration: 0
  RHipRoll:
    has_velocity_limits: true
    max_velocity: 4.712388975
    has_acceleration_limits: false
    max_acceleration: 0
  RHipYaw:
    has_velocity_limits: true
    max_velocity: 4.712388975
    has_acceleration_limits: false
    max_acceleration: 0
  RKneePitch:
    has_velocity_limits: true
    max_velocity: 4.712388975
    has_acceleration_limits: false
    max_acceleration: 0
  RShoulderPitch:
    has_velocity_limits: true
    max_velocity: 6.597344565
    has_acceleration_limits: false
    max_acceleration: 0
  RShoulderRoll:
    has_velocity_limits: true
    max_velocity: 6.597344565
    has_acceleration_limits: false
    max_acceleration: 0