controller_list:
  - name: fake_left_arm_controller
    joints:
      - LShoulderPitch
      - LShoulderRoll
      - LElbowPitch
  - name: fake_right_arm_controller
    joints:
      - RShoulderPitch
      - RShoulderRoll
      - RElbowPitch
  - name: fake_left_leg_controller
    joints:
      - LHipYaw
      - LHipRoll
      - LHipPitch
      - LKneePitch
      - LAnklePitch
      - LAnkleRoll
  - name: fake_right_leg_controller
    joints:
      - RHipYaw
      - RHipRoll
      - RHipPitch
      - RKneePitch
      - RAnklePitch
      - RAnkleRoll
  - name: fake_head_controller
    joints:
      - HeadYaw
      - HeadPitch