# hros5:
# trajectory controllers ---------------------------------------
left_arm_traj_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - LShoulderPitch
      - LShoulderRoll
      - LElbowPitch
      - j_wrist_l
      - j_gripper_l

right_arm_traj_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - RShoulderPitch
      - RShoulderRoll
      - RElbowPitch
      - j_wrist_r
      - j_gripper_r

head_traj_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - HeadYaw
      - HeadPitch

left_leg_traj_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - LHipYaw
      - LHipRoll
      - LHipPitch
      - LKneePitch
      - LAnklePitch
      - LAnkleRoll

right_leg_traj_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - RHipYaw
      - RHipRoll
      - RHipPitch
      - RKneePitch
      - RAnklePitch
      - RAnkleRoll
